interface Env {
	GEMINI_API_KEY: string;
	CORS_ALLOWED_ORIGINS: string;
	GROQ_API_KEY: string;
	SPAIID_APP_KEY: string;
	SPAIID_AUTH_KEY: string;
	FIREBASE_SERVICE_ACCOUNT_EMAIL: string;
	FIREBASE_PRIVATE_KEY: string;
	FIREBASE_PROJECT_ID: string;
	OTP_STORE: KVNamespace;
}
